package fjdb.kategames.squardle;

import fjdb.kategames.squardle.swing.PuzzleViewerFrame;
import fjdb.util.ListUtil;
import org.apache.groovy.util.Maps;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;

public class SquardlePuzzleGenerator {

    SquardleTools squardleTools = new SquardleTools();
    private WordGameSolver wordGameSolver;
    List<SquardleTools.Path> paths;

    public SquardlePuzzleGenerator() throws IOException {
        wordGameSolver = new WordGameSolver();
        paths = squardleTools.getPathsAndtransconfigurations();

    }

    private static void checkwordList9LetterWords() throws IOException {
        URL resource = SquardlePuzzleGenerator.class.getResource("/fjdb/kategames/squardle/wordList9Letters.txt");

        List<String> list = Files.lines(Paths.get(resource.getPath())).toList();

        List<String> nineUniqueLetterWords = new ArrayList<>();
        List<String> withDuplicateLetters = new ArrayList<>();

        for (String nineLetterWord : list) {
            Set<Character> uniqueChars = nineLetterWord.chars()
                    .mapToObj(c -> (char) c)
                    .collect(java.util.stream.Collectors.toSet());
            if (uniqueChars.size() == 9) {
                nineUniqueLetterWords.add(nineLetterWord);
            } else {
                withDuplicateLetters.add(nineLetterWord);
            }
        }

        for (String nineUniqueLetterWord : nineUniqueLetterWords) {
            System.out.println(nineUniqueLetterWord);
        }

    }

    public static void main(String[] args) throws IOException {

//        checkwordList9LetterWords();

        List<Puzzle> puzzles = new ArrayList<>();

        List<String> nineLetterWords = List.of(
//                "ABANDONED",
                "DEMOCRATS",
                "KILOBYTES",
                "abduction",
                "bachelors",
                "authorise",
                "bacterium",
                "bankrupts",
                "chlorides",
                "coastline",
                "coalmines",
                "crankiest",
                "cytoplasm",
                "detaching",
                "documents",
                "emulation",
                "factories",
                "filaments",
                "fluorides",
                "geraniums",
                "greyhound",
                "hazelnuts",
                "husbandry",
                "jubilance",
                "machinery"
        );

        List<String> nineUniqueLetterWords = new ArrayList<>();
        List<String> withDuplicateLetters = new ArrayList<>();

        for (String nineLetterWord : nineLetterWords) {
            Set<Character> uniqueChars = nineLetterWord.chars()
                    .mapToObj(c -> (char) c)
                    .collect(java.util.stream.Collectors.toSet());
            if (uniqueChars.size() == 9) {
                nineUniqueLetterWords.add(nineLetterWord);
            } else {
                withDuplicateLetters.add(nineLetterWord);
            }

        }

        Map<String, Integer> stringIntegerMap = nineLetterWordsNToZ();

        try {
            SquardlePuzzleGenerator generator = new SquardlePuzzleGenerator();

            for (Map.Entry<String, Integer> wordIndex : stringIntegerMap.entrySet()) {
                puzzles.add(generator.print(wordIndex.getKey(), wordIndex.getValue()));
            }
//            int i = 0;
//            for (String nineLetterWord : nineLetterWords) {
//                puzzles.add(generator.print(nineLetterWord, i));
//                i++;
//            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        new PuzzleViewerFrame(puzzles);
    }

    static int puzzleId = 25;
    public Puzzle print(String nineLetterWord, int index) throws IOException {
        nineLetterWord = nineLetterWord.toUpperCase();

        /*
1. Get a rando path for a 3x3 grid
2. Take a 9 letter word, and create the grid from that word and the path
3. Check that the word can be found in the grid using the path
4. Take a list of words from the 9 letter word, and see which can be found in the grid
5. Generate a Puzzle object with the letters and the list of found words
 */


//        String nineLetterWord = "ABANDONED";
//        SquardleTools.Path path = paths.get(new Random().nextInt(paths.size()));
        SquardleTools.Path path = paths.get(index);
        char[][] grid = squardleTools.gridFromWordAndPath(nineLetterWord, path);
        //convert 2-d grid to 1-d letters
        char[] letters = new char[9];
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                letters[i * 3 + j] = grid[i][j];
            }
        }

        List<String> words = wordGameSolver.getWords(nineLetterWord.toLowerCase());
        //turns words into upper case
        ArrayList<String> upperCaseWords = new ArrayList<>();
        words.forEach(word -> upperCaseWords.add(word.toUpperCase()));

        List<String> matches = squardleTools.findMatches(upperCaseWords, grid);
        matches.removeAll(excluded);

        Puzzle puzzle = new Puzzle(nineLetterWord.toUpperCase(), puzzleId++, letters, matches);
        System.out.println(puzzle.drawOutput());
//        System.out.println(matches.size());
        return puzzle;
    }

    private static Map<String, Integer> nineLetterWordsNToZ(){
        return Maps.of(
                "subatomic", 65,
                "vectorial", 32,
                "uncharted", 26,
                "triumphed", 42,
                "shambolic", 40,
                "repulsion", 39,
                "quicksand", 33,
                "phonecard", 31,
                "onslaught", 59,
                "nightmare", 49
                );
        //65, 32, 26, 42, 40, 39, 33, 31, 59, 30
    }

    private static List<String> excluded = excludedWords();

    private static List<String> excludedWords() {
        List<String> excludedWords = List.of(
                "CALO",
                "CALP",
                "CLOY",
                "CLOYS",
                "COLS",
                "COYS",
                "LACS",
                "LOCA",
                "LOYS",
                "MYCS",
                "OCAS",
                "POLS",
                "SALOP",
                "SALP",
                "SCOP",
                "TOCS",
                "TOLA",
                "TOLAS",
                "ARIOSE",
                "ARIOT",
                "ARIS",
                "ARISH",
                "ARUHE",
                "AURIS",
                "HOAR",
                "HOARS",
                "HOISE",
                "HORA",
                "HORI",
                "HORIS",
                "HORS",
                "HOURI",
                "HOURIS",
                "HOUT",
                "ROUTH",
                "ROUTHS",
                "RUTH",
                "RUTHS",
                "SHURA",
                "SORA",
                "SORI",
                "SOTH",
                "SOUARI",
                "SOUT",
                "TOISE",
                "TORA",
                "TORI",
                "TORS",
                "TORSE",
                "TORSI",
                "TOSE",
                "URAO",
                "URAOS",
                "AIRT",
                "ARES",
                "FARO",
                "FERIA",
                "FERIAS",
                "OTARIES",
                "RATO",
                "REFT",
                "RESAT",
                "RIAS",
                "SAFT",
                "SAIR",
                "SATORI",
                "SEIR",
                "SERA",
                "SERAC",
                "SERAI",
                "TAES",
                "TARO",
                "TORAS",
                "TORES",
                "TORI",
                "TREF",
                "TREFA",
                "TRES",
                "TRIAC",
                "TRIE",
                "ANIS",
                "ANEG",
                "ARUM",
                "ARUMS",
                "EAUS",
                "GEAN",
                "GEUM",
                "GEUMS",
                "GUAN",
                "GUAR",
                "INURE",
                "IURE",
                "MEUS",
                "MINA",
                "MINAE",
                "MINAR",
                "MUNI",
                "MUNIS",
                "MURA",
                "MURE",
                "NARE",
                "NIMS",
                "RAIS",
                "RANI",
                "RANIS",
                "RAUN",
                "REAN",
                "REMS",
                "RUME",
                "RUMINA",
                "SURA",
                "UNAI",
                "UNAIS",
                "URANISM",
                "UREMIA",
                "ACRED",
                "ARCO",
                "ARED",
                "ATOC",
                "ATOCS",
                "COSTARD",
                "CREM",
                "DERAT",
                "DERATS",
                "DRAC",
                "DRACO",
                "ECOS",
                "MERC",
                "MERCS",
                "MERCAT",
                "MERCATS",
                "MOCS",
                "MOER",
                "MOTS",
                "OCTA",
                "OMER",
                "OMERTA",
                "OSCAR",
                "RATOS",
                "RECTA",
                "RECTO",
                "RECTOS",
                "REOS",
                "SCRAT",
                "SOCA",
                "TACE",
                "BOIS",
                "BOKE",
                "BOKES",
                "BOKS",
                "BYKE",
                "BYKES",
                "EIKS",
                "ESKY",
                "ILKS",
                "KYBO",
                "KYES",
                "LISK",
                "LOKE",
                "LOKES",
                "OYES",
                "SEIK",
                "SEIL",
                "SEKT",
                "SIKE",
                "SKET",
                "SKIEY",
                "SKIO",
                "SKOL",
                "SKYTE",
                "TEIL",
                "YESK",
                "YOKS",
                "ARET",
                "ARETS",
                "KIBE",
                "LIBS",
                "LOBI",
                "OBES",
                "SOLI",
                "TYES",
                "YBET",
                "YEBO",
                "BUNCO",
                "CION",
                "CITO",
                "COIT",
                "DUCAT",
                "DUCI",
                "NOTA",
                "OTIC",
                "TABU",
                "TABUN",
                "TOUN",
                "UNCI",
                "UNCO",
                "ABLES",
                "ALBE",
                "ALEC",
                "BACH",
                "BACHES",
                "BACHS",
                "BAEL",
                "BELAH",
                "BELAHS",
                "BLAE",
                "BLAER",
                "BLAES",
                "BLORE",
                "BLORES",
                "CEORL",
                "CERO",
                "CHAL",
                "CHELA",
                "CHER",
                "EORL",
                "HABLE",
                "HAES",
                "HELO",
                "HERL",
                "LACHES",
                "LAER",
                "LAERS",
                "LAHS",
                "LECH",
                "LEHR",
                "LEHRS",
                "OLEA",
                "OLES",
                "ORLE",
                "ORLES",
                "REALO",
                "RECAL",
                "REHS",
                "RESH",
                "SECH",
                "SELAH",
                "SHEA",
                "SHEAL",
                "SHEOL",
                "ABRI",
                "ACERB",
                "ACETUM",
                "ACTURE",
                "BRACT",
                "BRAE",
                "BREI",
                "BRUME",
                "CABRIE",
                "CATE",
                "ETUI",
                "MERI",
                "MUIR",
                "RATU",
                "RIEM",
                "URAEI",
                "URATE",
                "UTERI",
                "ANKUS",
                "APTS",
                "BAPU",
                "BAPUS",
                "KATS",
                "KNAP",
                "KNAPS",
                "KUTA",
                "NATS",
                "PATU",
                "PATUS",
                "PRUTA",
                "PUKA",
                "SPUTA",
                "STUPA",
                "TAPU",
                "TAPUS",
                "TUPS",
                "TURK",
                "TURPS",
                "UPTA",
                "UPTAK",
                "URPS",
                "CEDI",
                "CEDIS",
                "CHLORID",
                "CHLORIDS",
                "CHODE",
                "DESI",
                "DHOL",
                "DIOL",
                "DORIES",
                "DORIS",
                "DORISE",
                "HEID",
                "HEIDS",
                "HODS",
                "HOISED",
                "LODS",
                "LOID",
                "LOIDS",
                "LOIR",
                "LORIES",
                "LORIS",
                "OHED",
                "ORDS",
                "RIDS",
                "RODES",
                "SIDH",
                "SIDHE",
                "AINE",
                "AITS",
                "CIEL",
                "CIELS",
                "CINE",
                "CIST",
                "CITS",
                "CONI",
                "CONIA",
                "CONIAS",
                "COSIE",
                "ELSIN",
                "ELTS",
                "ISTLE",
                "LEIS",
                "LENIS",
                "LENO",
                "LENOS",
                "LIAS",
                "LIEN",
                "LINOS",
                "LITS",
                "NEIST",
                "NELIS",
                "NILS",
                "NOIL",
                "NOILS",
                "ONIE",
                "OSTIA",
                "SAIC",
                "SAIN",
                "SAINE",
                "SIEN",
                "SILE",
                "SILEN",
                "SONE",
                "STIE",
                "TILS",
                "ALINE",
                "ALINES",
                "ANCE",
                "ANES",
                "ANIL",
                "CENS",
                "COALISE",
                "COLIES",
                "COLIN",
                "COLINS",
                "CONI",
                "CONIES",
                "CONSEIL",
                "EINA",
                "ENOL",
                "EOAN",
                "ISNA",
                "LIEN",
                "LIENS",
                "LIMN",
                "LIMNS",
                "MIEN",
                "MIENS",
                "MILO",
                "MINEOLA",
                "MINO",
                "MISE",
                "NIES",
                "NOES",
                "ONCES",
                "ONIE",
                "SECO",
                "SECONAL",
                "SENA",
                "SIEN",
                "SILANE",
                "AESC",
                "ANES",
                "ANKER",
                "ANKERS",
                "CESTI",
                "CRAN",
                "CRENA",
                "CRANKEST",
                "EARST",
                "ERST",
                "KERN",
                "KEST",
                "KETS",
                "KIER",
                "KIERS",
                "KINA",
                "KINE",
                "KINES",
                "KIST",
                "KNAR",
                "KNARS",
                "NITE",
                "NITER",
                "NITERS",
                "NITES",
                "RANKE",
                "RANKES",
                "REIK",
                "REINK",
                "REIS",
                "REIST",
                "REKNIT",
                "REKNITS",
                "RENK",
                "RETS",
                "RETSINA",
                "SCENA",
                "SCRAE",
                "SCRAN",
                "SEAN",
                "SIKER",
                "STEAN",
                "STEIN",
                "STEN",
                "STERNA",
                "TECS",
                "TINEA",
                "CAPO",
                "LOAM",
                "LOAMS",
                "LOTA",
                "LOTAS",
                "MALS",
                "MATY",
                "OLMS",
                "PACS",
                "PAMS",
                "PATY",
                "PLATY",
                "PLATYS",
                "PLOAT",
                "POAS",
                "SLATY",
                "TAMS",
                "TAYS",
                "ACNED",
                "CANG",
                "CANID",
                "CANT",
                "CANTED",
                "CHID",
                "CHINE",
                "CHINED",
                "CIDE",
                "DENI",
                "DICH",
                "ETNA",
                "GAED",
                "GAEN",
                "GANCH",
                "GANE",
                "GANT",
                "GANTED",
                "HIED",
                "HING",
                "INGATE",
                "NACH",
                "NIDE",
                "NIED",
                "TACH",
                "TAED",
                "TAEING",
                "TANH",
                "TANE",
                "TEIND",
                "COND",
                "CONTE",
                "DOUC",
                "DOUM",
                "DOUMS",
                "DOUT",
                "DOUTS",
                "MENO",
                "MENT",
                "MENTO",
                "METS",
                "MUTON",
                "NOTUM",
                "NOUT",
                "STEND",
                "STENO",
                "STOND",
                "STUM",
                "TEMS",
                "ALME",
                "ALUM",
                "ANOMIE",
                "LATI",
                "LOME",
                "LOTI",
                "MEOU",
                "MIAOU",
                "MOAI",
                "MOIT",
                "MOLA",
                "MONA",
                "MONAL",
                "MOTI",
                "NAOI",
                "NOME",
                "NOTAL",
                "NOUL",
                "TIMON",
                "TOLAN",
                "TOLU",
                "TOMIA",
                "TOMIAL",
                "ULAN",
                "AIREST",
                "ATES",
                "CERIA",
                "CESTA",
                "CESTOI",
                "EROS",
                "FESTA",
                "FETOR",
                "FETS",
                "FIAT",
                "FIATS",
                "FIER",
                "FIEST",
                "REIF",
                "RESTO",
                "RIFEST",
                "ROSET",
                "ROST",
                "SEIF",
                "SERIF",
                "SETA",
                "TOEA",
                "ALIF",
                "ALIT",
                "ALTS",
                "AMENT",
                "AMENTS",
                "ENTIA",
                "FIAT",
                "FIATS",
                "FILA",
                "ITAS",
                "LAMS",
                "LATEN",
                "LATI",
                "LATS",
                "LITAS",
                "MALI",
                "MALINE",
                "MATIN",
                "MENT",
                "MENTA",
                "METIF",
                "METS",
                "NEMA",
                "NEMAS",
                "SAMEN",
                "SATEM",
                "SATI",
                "SMALTI",
                "SMALTINE",
                "TALI",
                "TEMS",
                "TENIA",
                "TENIAS",
                "DELF",
                "DELO",
                "DELOS",
                "DERO",
                "DEROS",
                "DIEL",
                "EROS",
                "FLOE",
                "FLOES",
                "FLOR",
                "FLORID",
                "FLORS",
                "FLUOR",
                "FLUORID",
                "FLUORS",
                "LEIR",
                "LEIRS",
                "LOUED",
                "LUES",
                "ORIEL",
                "OULD",
                "OULDER",
                "RIEL",
                "ROLF",
                "ROLFED",
                "ROUE",
                "ROUES",
                "ROUL",
                "ROULES",
                "SELD",
                "SOLDE",
                "SOLDI",
                "SOLEI",
                "SOLER",
                "SORD",
                "ULES",
                "AGIN",
                "AMUS",
                "AREG",
                "GAES",
                "GAMS",
                "GARE",
                "GARS",
                "GAUM",
                "GAUMS",
                "GAUN",
                "GAUS",
                "GIES",
                "MAES",
                "MANI",
                "MANIES",
                "MANUS",
                "MARE",
                "MARES",
                "MARSE",
                "MASU",
                "MAUN",
                "MUSAR",
                "NAMS",
                "NAMU",
                "NIGER",
                "NIGERS",
                "RAGI",
                "RAMUS",
                "RASE",
                "REAGIN",
                "REGIUS",
                "SAGER",
                "SAGIER",
                "SEGAR",
                "USAGER",
                "DERO",
                "DREY",
                "GRYDE",
                "GYRE",
                "GYRED",
                "HOYED",
                "HYED",
                "HYNDE",
                "NYED",
                "OUNDY",
                "OYER",
                "RYND",
                "UNDE",
                "UNDY",
                "YERD",
                "ASTUN",
                "HAEN",
                "HAET",
                "HAETS",
                "HAST",
                "HEAST",
                "HEST",
                "HETS",
                "LEAS",
                "LUES",
                "LUNET",
                "LUNETS",
                "LUTEA",
                "NASUTE",
                "NAZE",
                "NAZES",
                "TULE",
                "TULES",
                "ULES",
                "ZEAS",
                "ABYS",
                "ADRY",
                "BHUNA",
                "BUNA",
                "BUND",
                "BUNDY",
                "DRYS",
                "SUBA",
                "BEIN",
                "BENI",
                "BICE",
                "BIEN",
                "BINAL",
                "JANE",
                "JUBE",
                "LAIC",
                "LIANE",
                "AYRE",
                "CAHIER",
                "CANEH",
                "CANIER",
                "CHAM",
                "CHAY",
                "CHINE",
                "HAYER",
                "HERY",
                "HYEN",
                "MACHE",
                "MACHER",
                "MACHI",
                "MANEH",
                "MANI",
                "RENAY",
                "RHINE",
                "ASCI",
                "BAST",
                "BASTO",
                "ISBA",
                "OSMIC",
                "SUBATOM",
                "TOMS",
                "TOSA",
                "TSUBA",
                "ARIL",
                "ARLE",
                "ARTEL",
                "AVEL",
                "CLARO",
                "CLART",
                "CLAVE",
                "CLOTE",
                "ILEA",
                "LARI",
                "LAVE",
                "LEVA",
                "LIART",
                "LIRA",
                "LIROT",
                "LOTE",
                "RAILE",
                "RALE",
                "RIAL",
                "RIALTO",
                "ROTL",
                "TELA",
                "TELIA",
                "TOLAR",
                "TOLE",
                "TRAVE",
                "VAIR",
                "VALI",
                "VARLET",
                "VELA",
                "VELAR",
                "VETO",
                "AHED",
                "HARN",
                "HART",
                "HARTEN",
                "RAHED",
                "RATH",
                "RATHE",
                "TAHR",
                "TEHR",
                "THAR",
                "UNETH",
                "UNHAT",
                "DRUPE",
                "DUIT",
                "DURE",
                "HEPT",
                "MURED",
                "MURTI",
                "MUTI",
                "PERDU",
                "PHUT",
                "PTUI",
                "PUER",
                "PUIR",
                "REDUIT",
                "TUMP",
                "TUMPED",
                "UMPED",
                "UMPH",
                "URDE",
                "AHIS",
                "AMBO",
                "ASCI",
                "BOHS",
                "BOMA",
                "BOMAS",
                "CHAS",
                "CHIS",
                "CHOLI",
                "CHOLIS",
                "HOLISM",
                "HOMA",
                "HOMAS",
                "HOMS",
                "ICHS",
                "LOMA",
                "LOMAS",
                "MOIL",
                "SAMBO",
                "SCHMO",
                "SHMO",
                "SICH",
                "LERP",
                "LUSER",
                "NOELS",
                "NOSER",
                "ONER",
                "OSIER",
                "PEON",
                "PERN",
                "PRONES",
                "PUER",
                "PULE",
                "PULER",
                "PULES",
                "PULS",
                "PULSION",
                "PURES",
                "PUSLE",
                "RONE",
                "RONES",
                "SENOR",
                "SERON",
                "SIEUR",
                "SLUE",
                "SORN",
                "SUPE",
                "UPROSE",
                "URES",
                "ASCI",
                "ASDIC",
                "CIDS",
                "DANS",
                "DUNS",
                "SADI",
                "SCUDI",
                "ACNODE",
                "CADE",
                "CARDON",
                "CARDPHONE",
                "DACE",
                "ECAD",
                "HOND",
                "HONDA",
                "PHON",
                "PRAD",
                "RADE",
                "AUGHT",
                "AULOS",
                "GONS",
                "GULA",
                "GULS",
                "HOLS",
                "HONS",
                "LOUGH",
                "SOLA",
                "SOUGH",
                "THON",
                "AHING",
                "AHINT",
                "EHING",
                "GERAH",
                "HERM",
                "HERMA",
                "HINGER",
                "IHRAM",
                "INGRAM",
                "MARG",
                "NIGHER",
                "RAHING",
                "THAR",
                "THARM",
                "THEGN",
                "THIG"
        );
        //add an s to each word to exclude plurals
        List<String> plurals = new ArrayList<>();
        for (String excludedWord : excludedWords) {
            plurals.add(excludedWord + "S");
        }
        plurals.addAll(excludedWords);
        return plurals;
    }

}
